/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_modsyn_abnormal_WinAbnormalSupport */

#ifndef _Included_org_modsyn_abnormal_WinAbnormalSupport
#define _Included_org_modsyn_abnormal_WinAbnormalSupport
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_modsyn_abnormal_WinAbnormalSupport
 * Method:    setDenormals
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_modsyn_abnormal_WinAbnormalSupport_setDenormals
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
